// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwBCNuN8NPk5mnwFGz5WN6K1-zZu7wEQQ',
    appId: '1:893562233767:web:58a829b5bf4c6334d18c82',
    messagingSenderId: '893562233767',
    projectId: 'drinks-app-26ad0',
    authDomain: 'drinks-app-26ad0.firebaseapp.com',
    storageBucket: 'drinks-app-26ad0.firebasestorage.app',
    measurementId: 'G-93WG1LNS60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vkUAhOL9Pday9LP2jflT3OwVDngypgA',
    appId: '1:893562233767:android:2fad0e095ac40e13d18c82',
    messagingSenderId: '893562233767',
    projectId: 'drinks-app-26ad0',
    storageBucket: 'drinks-app-26ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBNwk_Y2FLnhHl0hMtql2TvAhqgGBzJsM',
    appId: '1:893562233767:ios:db9204cc429a22ead18c82',
    messagingSenderId: '893562233767',
    projectId: 'drinks-app-26ad0',
    storageBucket: 'drinks-app-26ad0.firebasestorage.app',
    iosBundleId: 'com.example.drinksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBNwk_Y2FLnhHl0hMtql2TvAhqgGBzJsM',
    appId: '1:893562233767:ios:db9204cc429a22ead18c82',
    messagingSenderId: '893562233767',
    projectId: 'drinks-app-26ad0',
    storageBucket: 'drinks-app-26ad0.firebasestorage.app',
    iosBundleId: 'com.example.drinksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwBCNuN8NPk5mnwFGz5WN6K1-zZu7wEQQ',
    appId: '1:893562233767:web:daa402f292c32dead18c82',
    messagingSenderId: '893562233767',
    projectId: 'drinks-app-26ad0',
    authDomain: 'drinks-app-26ad0.firebaseapp.com',
    storageBucket: 'drinks-app-26ad0.firebasestorage.app',
    measurementId: 'G-KEC7LYMVDX',
  );
}
